# PlayBook to check for no update or upgrade git branches on remote and local
#
- hosts: backdrop_servers_local
  gather_facts: true
  tasks:
    - name: Script to check for no update or upgrade git branches on local
      ansible.builtin.script: /home/francis/ansible/backdrop_upgrade_made_easy/backdrop_step_1.sh local
