# PlayBook Step 2 in Backdrop Upgrade
#
- hosts: backdrop_servers_remote
  gather_facts: true
  tasks:
    - name: Script to exportConfigSync git commit and push current Production to git remote master prior to Upgrade
      ansible.builtin.script: /home/francis/ansible/backdrop_upgrade_made_easy/backdrop_step_2.sh prod 
