# PlayBook to check for no update or upgrade git branches on remote and local
#
- hosts: backdrop_servers_remote
  gather_facts: true
  tasks:
    - name: Script to check for no update or upgrade git branches on remote
      ansible.builtin.script: ~/ansible/backdrop_upgrade_made_easy/backdrop_step_1.sh prod
